### ISSUE TITLE
如何使用？

### ISSUE THREAD

**Issue by SMFDrummer** [chengdongqing/WeUI#1]
今天搞了一天依赖，头晕晕的，无论是挂魔法还是裸连，agp的依赖就是装不上，不走流量。

看了一下，单纯我自己用也实在用不到如此多的依赖，只是单纯的喜欢这套UI，很好看，使用的话我可能也只是用到UI相关的组件。

或者上传到Maven可能会好一些？

求大佬指点！

（Ps: 我自己的应用本身使用官方m3，我只想替换相关的控件样式，用不到如此多的功能性控件）

**Comment by chengdongqing** [comment]
请使用最新的非正式版Android studio试试。
如果还是报错请贴出详细报错信息。
